/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as DevenirIntervenantRouteImport } from './routes/devenir-intervenant'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as AideRouteImport } from './routes/aide'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingLaundryRouteImport } from './routes/booking/laundry'
import { Route as BookingCleaningRouteImport } from './routes/booking/cleaning'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const DevenirIntervenantRoute = DevenirIntervenantRouteImport.update({
  id: '/devenir-intervenant',
  path: '/devenir-intervenant',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const AideRoute = AideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingLaundryRoute = BookingLaundryRouteImport.update({
  id: '/booking/laundry',
  path: '/booking/laundry',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingCleaningRoute = BookingCleaningRouteImport.update({
  id: '/booking/cleaning',
  path: '/booking/cleaning',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/aide': typeof AideRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/dashboard': typeof DashboardRoute
  '/devenir-intervenant': typeof DevenirIntervenantRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/services': typeof ServicesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/booking/cleaning': typeof BookingCleaningRoute
  '/booking/laundry': typeof BookingLaundryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/aide': typeof AideRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/dashboard': typeof DashboardRoute
  '/devenir-intervenant': typeof DevenirIntervenantRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/services': typeof ServicesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/booking/cleaning': typeof BookingCleaningRoute
  '/booking/laundry': typeof BookingLaundryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/aide': typeof AideRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/dashboard': typeof DashboardRoute
  '/devenir-intervenant': typeof DevenirIntervenantRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/services': typeof ServicesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/booking/cleaning': typeof BookingCleaningRoute
  '/booking/laundry': typeof BookingLaundryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/aide'
    | '/cgv'
    | '/confidentialite'
    | '/dashboard'
    | '/devenir-intervenant'
    | '/how-it-works'
    | '/mentions-legales'
    | '/services'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/booking/cleaning'
    | '/booking/laundry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/aide'
    | '/cgv'
    | '/confidentialite'
    | '/dashboard'
    | '/devenir-intervenant'
    | '/how-it-works'
    | '/mentions-legales'
    | '/services'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/booking/cleaning'
    | '/booking/laundry'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/aide'
    | '/cgv'
    | '/confidentialite'
    | '/dashboard'
    | '/devenir-intervenant'
    | '/how-it-works'
    | '/mentions-legales'
    | '/services'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/booking/cleaning'
    | '/booking/laundry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AideRoute: typeof AideRoute
  CgvRoute: typeof CgvRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  DashboardRoute: typeof DashboardRoute
  DevenirIntervenantRoute: typeof DevenirIntervenantRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  ServicesRoute: typeof ServicesRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  BookingCleaningRoute: typeof BookingCleaningRoute
  BookingLaundryRoute: typeof BookingLaundryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devenir-intervenant': {
      id: '/devenir-intervenant'
      path: '/devenir-intervenant'
      fullPath: '/devenir-intervenant'
      preLoaderRoute: typeof DevenirIntervenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide': {
      id: '/aide'
      path: '/aide'
      fullPath: '/aide'
      preLoaderRoute: typeof AideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/laundry': {
      id: '/booking/laundry'
      path: '/booking/laundry'
      fullPath: '/booking/laundry'
      preLoaderRoute: typeof BookingLaundryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/cleaning': {
      id: '/booking/cleaning'
      path: '/booking/cleaning'
      fullPath: '/booking/cleaning'
      preLoaderRoute: typeof BookingCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AideRoute: AideRoute,
  CgvRoute: CgvRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  DashboardRoute: DashboardRoute,
  DevenirIntervenantRoute: DevenirIntervenantRoute,
  HowItWorksRoute: HowItWorksRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  ServicesRoute: ServicesRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  BookingCleaningRoute: BookingCleaningRoute,
  BookingLaundryRoute: BookingLaundryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
